### ISSUE TITLE
functionality needed

### ISSUE THREAD

**Issue by rismoney** [simondean/puppet-iis#1] opened 2012-08-09 00:43 UTC
is there any particular functionality that you want to see in this?  If I understand your overall vision, I can probably contribute.  I have written some provider code for windows and want to round out a bunch of functionality.

**Comment by mamtag** [comment] 2012-08-10 05:53
Hi I am working on simondan\iis module but getting issues-

1) I have Lunix CentOS(Master) machine and windows as Agent machine.
2) I have successfully install and build simondean\iis module on linux machine.
3) I have added iis class to window node.

Now when i am doing 'run puppet agent' from window machine getting error every time as below-

Error on run puppetagent cmd- 

Running Puppet agent on demand ...
info: Retrieving plugin
err: Could not retrieve catalog from remote server: Error 400 on SERVER: Could n
ot autoload iis_site: Could not autoload /etc/puppetlabs/puppet/modules/iis/lib/
puppet/provider/iis_site/iis_site.rb: no such file to load -- ../iis_object at /
etc/puppetlabs/puppet/modules/iis/manifests/init.pp:4 on node eqxomsdev
warning: Not using cache on failed catalog
err: Could not retrieve catalog; skipping run
Press any key to continue . . .

Please guide how i can come over from this error.One time along with error i got finished catalog.

**Comment by simondean** [comment] 2012-08-10 06:30
Hi. The module's reached its first real milestone of implementing enough IIS configuration to support using IIS to host ASP.NET and ASP.NET MVC web apps. That's meant supporting app pools, sites, apps and virtual directories. The main task for now is seeing how the module works for people and resolving any issues. The module has only been on Puppet Forge for a day or so, so I'm expecting more feedback as people start to use it. 

I'm interested in adding support for installing ad uninstalling IIS itself and its features but I'm thinking of putting that in a separate dedicated module.

**Comment by simondean** [comment] 2012-08-10 06:33
Hi mamtag. Could you open a new issue for me just to keep it separate from this one and I'll try and replicate your issue and see what the cause is.

**Comment by mamtag** [comment] 2012-08-10 06:41
HI Simon,

I have opened a new issue for puppet-iis.Please reply on that for any update.

Thanks a lot!

**Closed as completed** 2012-09-01 22:10 UTC

**Comment by PilchardFriendly** [comment] 2012-12-12 05:51
Hi Simon, great work - we've been playing with this over the last few days, and it has worked simply and easily.  

I was demoing it to a colleague, and she asked about SSL certificate support.  What do you think about that as a feature?

**Comment by JoeDog** [comment] 2015-06-10 13:03
I was also hoping for ssl certificate support. Pilchard requested that in 2012 but it's gone unanswered. Is this project still supported?
